---
deployment:
  tasks:
    - export GITPATH=/home/moom sdev/lacadev-git
    - export DEPLOYPATH=/home/moom sdev/public_html

    # Deploy Theme (chỉ copy những file thay đổi)
    - /usr/bin/rsync -av --delete --exclude='.git' $GITPATH/app/public/wp-content/themes/lacadev/ $DEPLOYPATH/wp-content/themes/lacadev/

    # Deploy Plugins
    - /usr/bin/rsync -av --exclude='.git' $GITPATH/app/public/wp-content/plugins/ $DEPLOYPATH/wp-content/plugins/
