---
deployment:
  tasks:
    - export GITPATH=/home/moomsdev/lacadev-git
    - export DEPLOYPATH=/home/moomsdev/public_html

    - echo "=== Đang deploy theme lacadev ==="
    - /usr/bin/rsync -av --delete --exclude='.git' $GITPATH/app/public/wp-content/themes/lacadev/ $DEPLOYPATH/wp-content/themes/lacadev/

    - echo "=== Đang deploy plugins ==="
    - /usr/bin/rsync -av --exclude='.git' $GITPATH/app/public/wp-content/plugins/ $DEPLOYPATH/wp-content/plugins/
